- name: running a comand
  hosts: all
  remote_user: kingsley
  become: True
  tasks:
    - name: Run ls command
      shell: ls

    - name: remove apache2
      service:
        name: apache2
      #apt: apache2
        state: restarted

      