name: CI
on: workflow_dispatch

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: setup ssh
          shell: bash
          run: |
            service ssh status
            eval 'ssh-agent -s'
        - name: Run playbook
          uses: dawidd6/action-ansible-playbook@v2.8.0
          with:
            playbook: ansible.yml
            inventory: inventory.yml
            directory: ./