name: CI
on: workflow_dispatch

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: setup ssh
          shell: bash
          run: |
            service ssh status
            eval 'ssh-agent -s'
            